import React from "react";
import Navbar from "../components/shared/Navbar";
import { FaPhoneAlt } from "react-icons/fa";
import { HiOutlineMail } from "react-icons/hi";
import Footer from "../components/shared/footer/Footer";
export const metadata = {
  title: "Return Refund Policy",
  description: "Generated by create next app",
};
export default function ReturnRefundPolicy() {

  return (
    <section className="bg-gray-50 min-h-screen">
      <Navbar />

      <div className="max-w-7xl mx-auto px-4 md:px-16 py-12 text-gray-600">
        <h1 className="text-xl md:text-3xl font-bold text-center mb-8 text-gray-800">
          Return & Refund Policy
        </h1>

        <section className="space-y-6 bg-white shadow-md rounded-2xl p-6 md:p-10">
          <p className="border-b pb-5 border-gray-300 text-gray-600">
            Thank you for shopping with <strong>Smart Shop</strong>.  
            We value your satisfaction and strive to ensure a smooth shopping experience.  
            Please read our Return & Refund Policy carefully to understand your rights and obligations.
          </p>

          
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            1. Eligibility for Return
          </h2>
          <p>
            Products are eligible for return or exchange if they meet the following conditions:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>The item must be unused, unwashed, and in its original condition.</li>
            <li>The product must include all original packaging, tags, and accessories.</li>
            <li>Return request must be made within <strong>7 days</strong> of delivery.</li>
            <li>Electronics and hygiene-related items are non-returnable unless defective.</li>
          </ul>

         
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            2. Non-returnable Items
          </h2>
          <p>
            The following products are not eligible for return or refund:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Products purchased during clearance or flash sales.</li>
            <li>Personal care, cosmetics, or hygiene-related products.</li>
            <li>Digital goods and subscriptions.</li>
            <li>Gift cards or vouchers.</li>
          </ul>

        
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            3. Damaged or Defective Products
          </h2>
          <p>
            If you receive a damaged or defective product, please contact our support team
            within <strong>48 hours</strong> of receiving the item.  
            We will investigate and offer a replacement or full refund as applicable.
          </p>
          <p>
            Please include your order ID, product photos, and a brief description of the issue when contacting us.
          </p>

          
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            4. Refund Process
          </h2>
          <p>
            Once your returned product is received and inspected, we will notify you via email
            regarding the approval or rejection of your refund.
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Approved refunds will be processed within <strong>7–10 business days</strong>.</li>
            <li>The refund will be issued to your original payment method.</li>
            <li>Delivery charges are non-refundable unless the return is due to our error.</li>
          </ul>

         
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            5. Order Cancellation
          </h2>
          <p>
            Orders can be canceled before shipment.  
            Once the product has been dispatched, cancellation will not be possible.  
            To cancel, please contact our customer service immediately after placing the order.
          </p>

        
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            6. Exchange Policy
          </h2>
          <p>
            We allow exchanges for the same product type (e.g., size or color variation)
            if available in stock. Exchange requests must be made within 7 days of delivery.
          </p>

         
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            7. Contact Us
          </h2>
          <p>
            For any return, refund, or exchange queries, please contact our support team:
          </p>

          <div className="bg-gray-50 shadow-inner rounded-xl py-8 mt-6">
            <p className="text-center text-xl font-bold mb-4">
              Need Assistance?
            </p>
            <ul className="text-center space-y-2">
              <li>
                <strong>Support Hours:</strong> Every day from 10:00 AM to 8:00 PM
              </li>
              <div className="flex justify-center md:justify-around items-center flex-col md:flex-row mt-5 gap-6">
                <li className="flex items-center gap-2 text-lg">
                  <FaPhoneAlt className="text-green-600" />
                  <div>
                    <strong>Call us</strong> <br /> +8801XXXXXXXXX
                  </div>
                </li>
                <li className="flex items-center gap-2 text-lg">
                  
                  <div>
                    <strong> 💌Email Us</strong> <br />
                    <a
                      href="mailto:support@smartshop.com.bd"
                      className="text-blue-600 underline"
                    >
                      support@smartshop.com.bd
                    </a>
                  </div>
                </li>
              </div>
            </ul>
          </div>
        </section>
      </div>
      <Footer/>
    </section>
  );
}
