import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import ChatWidget from "./components/Chatbot/ChatWidget";
import Ai from "./components/ai/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Smart Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}

        // ADD THIS PROP
        suppressHydrationWarning={true}
      >
        <AuthProvider>
          {children}
          <Ai />
          {/* <ChatWidget></ChatWidget> */}
        </AuthProvider>
      </body>
    </html>
  );
}
