import React from "react";
import Navbar from "../components/shared/Navbar";
import Footer from "../components/shared/footer/Footer";
export const metadata = {
  title: "Privacy Policy",
  description: "Generated by create next app",
};
export default function PrivacyPolicy() {
  
  return (
    <section className="bg-gray-50 min-h-screen">
      <Navbar />

      <div className="max-w-7xl mx-auto px-4 md:px-16 py-12 text-gray-600">
        <h1 className="text-2xl md:text-3xl font-bold text-center mb-8 text-gray-800">
          Privacy Policy
        </h1>

        <section className="space-y-6 bg-white shadow-md rounded-2xl p-6 md:p-10">
          <p className="border-b pb-5 border-gray-300 text-gray-600">
            In order for the website to provide a safe and useful service, it is
            important for <strong>Smart Shop</strong> to collect, use, and share
            personal information. By using our platform, you agree to the terms
            described in this Privacy Policy.
          </p>

          <h2 className="text-xl font-semibold text-gray-800 mt-8">1. Collection</h2>
          <p>
            Information posted on <strong>Smart Shop</strong> is publicly
            available. If you choose to provide us with personal information, you
            are consenting to the transfer and storage of that information on our
            secure servers.
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Email address, contact information, and sometimes financial information.</li>
            <li>Computer sign-on data, statistics on page views, traffic, and response to ads.</li>
            <li>Users' IP address and standard web log information.</li>
          </ul>

          
          <h2 className="text-xl font-semibold text-gray-800 mt-8">2. Use</h2>
          <p>We use users’ personal information to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Provide and improve our services.</li>
            <li>Resolve disputes, collect fees, and troubleshoot problems.</li>
            <li>Encourage safe trading and enforce our policies.</li>
            <li>Customize users’ experience and measure interest in our services.</li>
            <li>Inform users about new services, offers, and updates.</li>
            <li>Send marketing and promotional messages according to preferences.</li>
          </ul>

          
          <h2 className="text-xl font-semibold text-gray-800 mt-8">3. Cookie Policy</h2>
          <h3 className="text-xl font-medium mt-2">What Are Cookies?</h3>
          <p>
            Cookies are small text files stored on your device when you visit a
            website. They help improve your browsing experience — for example, to
            keep you signed in, remember preferences, and show relevant content.
          </p>

          <h3 className="text-xl font-medium mt-4">Cookies and Personal Data</h3>
          <p>
            We use cookies and similar technologies to personalize content and ads,
            provide social media features, send promotional materials, and analyze
            traffic. Limited cookie data may be shared with our partners (Google,
            Facebook, WebEngage, etc.).
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Session Cookies – Required to operate our service.</li>
            <li>Preference Cookies – Used to remember your settings.</li>
            <li>Security Cookies – Required for protection and fraud prevention.</li>
          </ul>
          <p>
            You can manage or disable cookies in your browser settings. Some
            features may not function properly if cookies are disabled.
          </p>

          
          <h2 className="text-xl font-semibold text-gray-800 mt-8">4. Disclosure</h2>
          <p>
            We do not sell or rent users’ personal information to third parties
            for marketing purposes without your explicit consent. However, we may
            disclose information:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>To comply with legal requirements or enforce policies.</li>
            <li>To protect anyone’s rights, property, or safety.</li>
            <li>With sellers or partners you’ve interacted with for better service.</li>
          </ul>

          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            5. Communication and Email Tools
          </h2>
          <p>
            You agree to receive marketing communications about products and
            services unless you choose to opt out. You can unsubscribe anytime by
            following the link provided in our emails.
          </p>
          <p>We may automatically scan messages to detect spam or harmful content.</p>

          
          <h2 className="text-xl font-semibold text-gray-800 mt-8">6. Security</h2>
          <p>
            We use encryption, passwords, and secure servers to protect your
            personal information against unauthorized access. Your privacy is our
            top priority.
          </p>

        
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            7. Unsubscribe Information
          </h2>
          <p>
            You can review or remove your information anytime by contacting us at{" "}
            <a href="mailto:support@smartshop.com.bd" className="text-blue-600 underline">
              support@smartshop.com.bd
            </a>
            . You can also unsubscribe via the link at the bottom of our emails.
          </p>
          <p>
            Smart Shop uses Google Analytics and remarketing tools. You can opt
            out anytime using Google Ads Preferences Manager.
          </p>

          
          <div className="bg-gray-50 shadow-inner rounded-xl py-8 mt-10">
            <p className="text-center text-2xl font-bold mb-4">
              Want to get in touch quickly?
            </p>
            <ul className="text-center space-y-2">
              <li>
                <strong>Support Hours:</strong> Every day from 10:00 AM to 8:00 PM
              </li>
              <div className="flex justify-center md:justify-around items-center flex-col md:flex-row mt-5 gap-6">
                <li className="flex items-center gap-2 text-lg">
                  
                  <div>
                    <strong>📞 Call us</strong> <br /> +8801XXXXXXXXX
                  </div>
                </li>
                <li className="flex items-center gap-2 text-lg">
                 
                  <div>
                    <strong>💌 Email Us</strong> <br />
                    <a
                      href="mailto:support@smartshop.com.bd"
                      className="text-blue-600 underline"
                    >
                      support@smartshop.com.bd
                    </a>
                  </div>
                </li>
              </div>
            </ul>
          </div>
        </section>
      </div>
      <Footer/>
    </section>
  );
}
