import React from "react";
import Navbar from "../components/shared/Navbar";
import { ShieldCheck, Scale, AlertTriangle } from "lucide-react";
import Footer from "../components/shared/footer/Footer";
export const metadata = {
  title: "Term and Conditions",
  description: "Generated by create next app",
};
export default function TermsAndConditions() {
  return (
    <section className="bg-gray-50 min-h-screen">
      <Navbar />

      <div className="max-w-7xl mx-auto px-4 md:px-16 py-12 text-gray-600">
        <h1 className="text-xl md:text-3xl font-bold text-center mb-8 text-gray-800">
          Terms and Conditions
        </h1>

        <section className="space-y-6 bg-white shadow-md rounded-2xl p-6 md:p-10">
          <p className="border-b pb-5 border-gray-300 text-gray-600">
            Welcome to <strong>Smart Shop</strong>! By accessing or using our
            website, you agree to comply with and be bound by the following
            Terms and Conditions. Please read them carefully before using our
            services.
          </p>

          
          <h2 className="text-xl font-semibold text-gray-800 mt-8 flex items-center gap-2">
            <ShieldCheck className="text-blue-600" size={24} />
            1. General Terms
          </h2>
          <p>
            Smart Shop is an online marketplace that allows users to buy and sell
            products conveniently. All users must use the platform responsibly
            and lawfully. We reserve the right to modify or terminate our
            services at any time without prior notice.
          </p>

          
          <h2 className="text-xl font-semibold text-gray-800 mt-8 flex items-center gap-2">
            <Scale className="text-green-600" size={24} />
            2. Account Responsibility
          </h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>You must be at least 18 years old to register an account.</li>
            <li>
              You are responsible for maintaining the confidentiality of your
              account credentials.
            </li>
            <li>
              Any activity under your account will be considered your
              responsibility.
            </li>
            <li>
              Smart Shop reserves the right to suspend or terminate accounts
              violating these terms.
            </li>
          </ul>

         
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            3. Product Listing and Pricing
          </h2>
          <p>
            We strive to provide accurate product descriptions and prices.
            However, errors may occur. If any product is listed with an incorrect
            price or description, Smart Shop reserves the right to correct the
            information or cancel the order.
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>All prices are shown in US Dollars (USD).</li>
            <li>
              Discounts, offers, or coupons are subject to availability and may
              change anytime.
            </li>
            <li>
              Orders will only be confirmed upon successful payment or COD
              verification.
            </li>
          </ul>

        
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            4. Payment and Delivery
          </h2>
          <p>
            Smart Shop supports multiple payment methods including Cash on
            Delivery (COD), Mobile Banking (bKash, Nagad, Rocket), and debit/credit cards.
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Delivery timelines may vary depending on product and location.</li>
            <li>
              Delivery charges are displayed at checkout and may vary for
              different regions.
            </li>
            <li>
              In case of delivery failure due to an incorrect address, additional
              charges may apply.
            </li>
          </ul>

         
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            5. Returns and Refunds
          </h2>
          <p>
            If you receive a damaged or defective product, you may request a
            return or refund within 3 days of delivery. To know more, please read
            our{" "}
            <a
              href="/returnRefundPolicy"
              className="text-blue-600 underline"
            >
              Return & Refund Policy
            </a>
            .
          </p>

         
          <h2 className="text-xl font-semibold text-gray-800 mt-8 flex items-center gap-2">
            <AlertTriangle className="text-red-600" size={24} />
            6. Prohibited Activities
          </h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>Posting false, misleading, or illegal content.</li>
            <li>Using the platform for fraudulent or harmful purposes.</li>
            <li>Attempting to hack or disrupt Smart Shop’s system.</li>
            <li>Violating any local, national, or international law.</li>
          </ul>

          
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            7. Limitation of Liability
          </h2>
          <p>
            Smart Shop is not liable for indirect, incidental, or consequential
            damages resulting from the use of our services, delays, or product
            unavailability. We are committed to ensuring user satisfaction within
            reasonable business practices.
          </p>

         
          <h2 className="text-xl font-semibold text-gray-800 mt-8">
            8. Changes to Terms
          </h2>
          <p>
            Smart Shop may update or modify these Terms and Conditions at any
            time. Any updates will be posted on this page, and continued use of
            the website will signify your acceptance of the changes.
          </p>

         
          <div className="bg-gray-50 shadow-inner rounded-xl py-8 mt-10">
            <p className="text-center text-xl font-bold mb-4">
              Contact Information
            </p>
            <ul className="text-center space-y-2">
              <li>
                <strong>Support Hours:</strong> Every day from 10:00 AM to 8:00 PM
              </li>
              <div className="flex justify-around items-center mt-5">
                <li>
                  <strong>📞 Call us</strong> <br />  +8801XXXXXXXXX
                </li>
                <li>
                  <strong>💌 Email Us</strong> <br />
                  <a
                    href="mailto:support@smartshop.com.bd"
                    className="text-blue-600 underline"
                  >
                    support@smartshop.com.bd
                  </a>
                </li>
              </div>
            </ul>
          </div>
        </section>
      </div>
      <Footer/>
    </section>
  );
}
